### ISSUE TITLE
As a player I want to have a basic functioning inventory

### ISSUE THREAD

**Issue by Davidek523** [ultimateownsz/PySeas#41] opened 2024-10-28 13:41 UTC
- [ ] The player can remove items from his inventory.
- [ ] The player can add items to his inventory.
- [ ] The player can open the inventory and look through its items.
- [ ] The player can take a item from his inventory to use it, it wil also remove the item from the inventory.

**Comment by AnSiChen** [comment] 2024-11-11 02:36
**Proposed Plan:** Thank you for opening this issue! Below is my analysis of the current state of the inventory system, along with a proposed plan for improvements. I’d love to hear any feedback or preferences the team may have before I get started.

**Current State:** The inventory system in src/inventory is partially implemented. The class exists but is incomplete, and there are no tests for any part of the inventory yet.

**Status:** The add_item function, currently called extension(), needs further development. I’ll update it and connect it to the "Buying" feature, but since "Buying" also has issues and is incomplete, this could serve as a starting point for creating a more cohesive connection. However, I won’t focus on "Buying" in depth at this stage.

**Structure Change:** Items are currently stored in a list, which may become difficult to manage as the inventory grows. To improve organization and access speed, I plan to switch to dictionaries, or potentially create an Item class if the complexity justifies it (please let me know if the community has preferences on this). Using dictionaries could pave the way for item categories like weapons, upgrades, armor, and food, making it easier for players to search and organize items as needed.

**Error Handling:** Currently minimal; I’ll add error handling to ensure the system provides clear feedback to users when they try to add or remove items. Since I didn’t see any existing message or interaction JSON file, I’ll either hardcode messages for now or, if appropriate, connect them to a dedicated JSON file for inventory-specific issues. This approach will help modularize error handling from the start, making it easier to add multilingual support in the future or move it around when necessary without having to go line by line (ideally). Please let me know if this aligns with the project’s goals or if there are any preferences.

**UI:** I’ll link the inventory system to the UI with placeholders for now, focusing on functionality rather than design. Since there appears to be a plan to integrate a Virtual Book feature later, it seems best to prioritize basic functionality over design details for now. Additionally, I assume “items” refers to the objects in Treasure+.png (correct me if this assumption is off).

If there are further comments or suggestions, please let me know. Once confirmed, please assign this issue to me if appropriate. Thank you!

**Comment by ultimateownsz** [comment] 2024-11-11 09:12
Hey I have replied to your query per section below!

> **Proposed Plan:** Thank you for opening this issue! Below is my analysis of the current state of the inventory system, along with a proposed plan for improvements. I’d love to hear any feedback or preferences the team may have before I get started.

> **Current State:** The inventory system in src/inventory is partially implemented. The class exists but is incomplete, and there are no tests for any part of the inventory yet.
> 
> **Status:** The add_item function, currently called extension(), needs further development. I’ll update it and connect it to the "Buying" feature, but since "Buying" also has issues and is incomplete, this could serve as a starting point for creating a more cohesive connection. However, I won’t focus on "Buying" in depth at this stage.
> 
> **Structure Change:** Items are currently stored in a list, which may become difficult to manage as the inventory grows. To improve organization and access speed, I plan to switch to dictionaries, or potentially create an Item class if the complexity justifies it (please let me know if the community has preferences on this). Using dictionaries could pave the way for item categories like weapons, upgrades, armor, and food, making it easier for players to search and organize items as needed.
> 
> **Error Handling:** Currently minimal; I’ll add error handling to ensure the system provides clear feedback to users when they try to add or remove items. Since I didn’t see any existing message or interaction JSON file, I’ll either hardcode messages for now or, if appropriate, connect them to a dedicated JSON file for inventory-specific issues. This approach will help modularize error handling from the start, making it easier to add multilingual support in the future or move it around when necessary without having to go line by line (ideally). Please let me know if this aligns with the project’s goals or if there are any preferences.
> 
> **UI:** I’ll link the inventory system to the UI with placeholders for now, focusing on functionality rather than design. Since there appears to be a plan to integrate a Virtual Book feature later, it seems best to prioritize basic functionality over design details for now. Additionally, I assume “items” refers to the objects in Treasure+.png (correct me if this assumption is off).
> 
> If there are further comments or suggestions, please let me know. Once confirmed, please assign this issue to me if appropriate. Thank you!

Proposed plan: I think you are referring to the old code from the CLI game, yes the command line interface inventory is very simple but needs to be adjusted. For Pygame we are working in the GUI which means Graphical User Interface, you might want to check that out.

Status: Yes this is an overall good idea!

Structure change: I like the idea of using a dictionary with json properties. Updating a json file for inventory is overall a better way to store all the logics of how the inventory holds all the items etc.

Error handling: If you have ideas to add multilingual support already in some capacity it would be a good start. I'm not sure how this would work, have to see some examples for it, but I like it overall!

UI: Yes functionality with some placeholders are a good practice. To answer your question about items, yes in the Assets' folder we have for example the Treasure+.

@Davidek523 assigned you to the issue, let me know if you have direct access.

**Closed** 2024-12-17 11:53 UTC
